"use client";

import { useState } from "react";
import { Loader2, Save, Trash2, UserRound } from "lucide-react";
import { useRouter } from "next/navigation";
import type { Lead } from "@/lib/database.types";

export function CustomerProfileEditor({ customer }: { customer: Lead }) {
  const router = useRouter();
  const [form, setForm] = useState({ fullName: customer.full_name, company: customer.company ?? "", email: customer.email, phone: customer.phone ?? "", notes: customer.notes ?? "" });
  const [busy, setBusy] = useState<"save" | "delete" | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy("save"); setNotice(null); const response = await fetch(`/api/admin/customers/${customer.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setBusy(null); if (!response.ok) { setNotice("No se pudieron guardar los cambios."); return; } setNotice("Perfil actualizado."); router.refresh(); };
  const remove = async () => { if (!window.confirm("¿Eliminar este perfil y todas sus cotizaciones? Esta acción no se puede deshacer.")) return; setBusy("delete"); const response = await fetch(`/api/admin/customers/${customer.id}`, { method: "DELETE" }); if (!response.ok) { setBusy(null); setNotice("No se pudo eliminar el perfil."); return; } router.push("/admin/leads"); router.refresh(); };
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <form onSubmit={save} className="overflow-hidden rounded-xl border border-brand-border bg-white"><div className="flex items-center gap-3 border-b border-brand-border bg-slate-50 p-5"><span className="grid h-10 w-10 place-items-center rounded-full bg-brand-navy text-white"><UserRound className="h-5 w-5" /></span><div><p className="font-mono text-[10px] tracking-[.16em] text-brand-blue">PERFIL DEL CLIENTE</p><h2 className="font-semibold text-brand-navy">Datos y seguimiento comercial</h2></div></div><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Nombre completo"><input required value={form.fullName} onChange={(event) => set("fullName", event.target.value)} /></Field><Field label="Empresa"><input value={form.company} onChange={(event) => set("company", event.target.value)} placeholder="Empresa o razón social" /></Field><Field label="Correo electrónico"><input required type="email" value={form.email} onChange={(event) => set("email", event.target.value)} /></Field><Field label="Teléfono"><input value={form.phone} onChange={(event) => set("phone", event.target.value)} /></Field><Field label="Notas del cliente" full><textarea rows={3} value={form.notes} onChange={(event) => set("notes", event.target.value)} placeholder="Proceso, industria, preferencias o contexto comercial" /></Field></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-brand-border bg-slate-50 p-4"><button disabled={busy !== null} className="flex items-center gap-2 rounded-md bg-brand-navy px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-navy-dark disabled:opacity-60">{busy === "save" ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Guardar perfil</button><button type="button" onClick={remove} disabled={busy !== null} className="flex items-center gap-2 rounded-md border border-red-200 px-3 py-2 text-xs font-semibold text-red-600 hover:bg-red-50 disabled:opacity-60">{busy === "delete" ? <Loader2 className="h-4 w-4 animate-spin" /> : <Trash2 className="h-3.5 w-3.5" />}Eliminar cliente</button></div>{notice && <p className={`mx-5 mb-5 rounded-md px-3 py-2 text-xs ${notice === "Perfil actualizado." ? "bg-green-50 text-green-700" : "bg-red-50 text-red-600"}`}>{notice}</p>}</form>;
}
function Field({ label, children, full }: { label: string; children: React.ReactNode; full?: boolean }) { return <label className={`block text-xs font-semibold text-slate-500 ${full ? "sm:col-span-2" : ""}`}>{label}<span className="mt-1.5 block [&_input]:w-full [&_input]:rounded-md [&_input]:border [&_input]:border-brand-border [&_input]:px-3 [&_input]:py-2 [&_input]:text-sm [&_textarea]:w-full [&_textarea]:rounded-md [&_textarea]:border [&_textarea]:border-brand-border [&_textarea]:px-3 [&_textarea]:py-2 [&_textarea]:text-sm">{children}</span></label>; }
